baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"

theme = 'MainRoad'

publishDir = "../docs" 



tags = ["blog", "responsive", "widgets", "rss", "disqus", "google analytics", "wordpress"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]

