baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo SITE"

theme = "GridLayoutBasic"

publishDir______ = "../docs" 



tags = ["blog", "responsive", "widgets", "rss", "disqus", "google analytics", "wordpress"]
features = ["blog", "responsive", "widgets", "rss", "disqus", "wordpress"]

[params]
  mainSections = ["blog", "docs"]
  saying = "holy root"
  debug_mode = "t"
  debug_mode_verbose = ""

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

